name: Build Paper

on: [push, pull_request]


jobs:
  build-paper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout scipy_proceedings
      uses: actions/checkout@v3
      with:
        repository: scipy-conference/scipy_proceedings.git
        ref: 042d636c45c94340ab27c3f9f867e2fe059d63d2
    - name: Checkout scipy-2023-presentation
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip' # caching pip dependencies

    # This doesn't actually work with latex unfortunately
    # - name: Install apt dependencies
    #   uses: awalsh128/cache-apt-pkgs-action@latest
    #   with:
    #     packages: texlive-latex-recommended texlive-fonts-recommended texlive-fonts-extra texlive-publishers texlive-base texlive-bibtex-extra
    #     execute_install_scripts: true

    # Installing latex is slow, so instead we use the texlive-action.
    # - name: Install apt dependencies
    #   run: sudo apt install texlive-latex-recommended texlive-fonts-recommended texlive-fonts-extra texlive-publishers texlive-base texlive-bibtex-extra

    - name: Build the paper
      uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install -r ${GITHUB_WORKSPACE}/scipy_proceedings/requirements.txt
          cd ${GITHUB_WORKSPACE}/scipy_proceedings
          cp -R ${GITHUB_WORKSPACE}/scipy-2023-presentation/paper/ papers/01_arrayapi
          ./make_paper.sh papers/01_arrayapi/

    # TODO: we could instead upload the paper to a branch on the repo using
    # https://github.com/marketplace/actions/deploy-to-github-pages
    - name: Upload the paper as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: built-paper
        path: ${{ github.workspace }}/scipy_proceedings/output/01_arrayapi/paper.pdf
        if-no-files-found: error
